export type Product = {
  brand: "SKIN1004" | "CELIMAX" | "MEDICUBE";
  name: string;
  size: string;
  eyebrow: string;
  description: string;
  skin: string;
  use: string;
  price: number;
  transfer: number;
  image: string;
  imageScene?: boolean;
  accent: string;
  soldOut?: boolean;
};

export const products: Product[] = [
  {
    brand: "SKIN1004",
    name: "Madagascar Centella Tone Brightening Capsule Ampoule",
    size: "100 ml",
    eyebrow: "Luminosidad · tono uniforme",
    description: "Ampolla iluminadora con niacinamida, ácido tranexámico, vitamina C derivada y centella asiática. Ayuda a mejorar gradualmente la apariencia del tono desparejo y las marcas visibles mientras aporta hidratación y calma.",
    skin: "Piel normal, seca o mixta con opacidad o marcas visibles.",
    use: "Aplicá 2 o 3 gotas después del tónico, de mañana o de noche.",
    price: 47900,
    transfer: 44910,
    image: "/products-v11/skin1004-tone.webp",
    accent: "#c8d8be",
    soldOut: true,
  },
  {
    brand: "SKIN1004",
    name: "Madagascar Centella Light Cleansing Oil",
    size: "200 ml",
    eyebrow: "Doble limpieza · maquillaje",
    description: "Aceite limpiador liviano con centella asiática y aceites de origen vegetal. Disuelve protector solar, maquillaje, sebo e impurezas y, al contacto con agua, se transforma en una emulsión lechosa fácil de enjuagar.",
    skin: "Todo tipo de piel, incluso mixta o sensible.",
    use: "Masajeá sobre el rostro seco, emulsioná con agua y enjuagá.",
    price: 47900,
    transfer: 47610,
    image: "/products-v11/skin1004-cleansing.webp",
    accent: "#e9d2a7",
    soldOut: true,
  },
  {
    brand: "SKIN1004",
    name: "Hyalu-Cica Water-Fit Sun Serum SPF50+ PA++++",
    size: "50 ml",
    eyebrow: "Protección solar · hidratación",
    description: "Protector solar de textura sérum que combina centella asiática y ácido hialurónico. Se absorbe rápido, no deja rastro blanco y ofrece un acabado luminoso y liviano que funciona muy bien debajo del maquillaje.",
    skin: "Piel normal, seca, mixta o sensible.",
    use: "Usá una cantidad generosa como último paso de la mañana y reaplicá.",
    price: 42900,
    transfer: 44910,
    image: "/products-v11/skin1004-sun.webp",
    accent: "#b9d8e8",
  },
  {
    brand: "SKIN1004",
    name: "Madagascar Centella Watergel Sheet Ampoule Mask",
    size: "25 ml",
    eyebrow: "Calma · hidratación intensa",
    description: "Mascarilla de tela con centella asiática, glicerina, manzanilla y ácido hialurónico. Aporta una sensación refrescante e hidratación inmediata cuando la piel se siente tirante o apagada.",
    skin: "Piel normal, mixta, sensible o deshidratada.",
    use: "Dejá actuar de 10 a 20 minutos y masajeá el excedente. No enjuagues.",
    price: 7900,
    transfer: 7650,
    image: "/products-v11/skin1004-mask.webp",
    imageScene: true,
    accent: "#d6c39f",
  },
  {
    brand: "CELIMAX",
    name: "Pore + Dark Spot Brightening Pad",
    size: "40 pads / 100 ml",
    eyebrow: "Manchas · luminosidad",
    description: "Pads tonificantes con niacinamida, ácido tranexámico, arbutina y ácido hialurónico. Ayudan a mejorar gradualmente la apariencia de manchas, marcas post-imperfecciones y tono desparejo mientras hidratan.",
    skin: "Todo tipo de piel con tono irregular o marcas visibles.",
    use: "Deslizá un pad después de limpiar o usalo como mini mascarilla puntual.",
    price: 39900,
    transfer: 44910,
    image: "/products-v11/celimax-pad.webp",
    accent: "#efd35f",
  },
  {
    brand: "CELIMAX",
    name: "The Real Noni Starter Kit",
    size: "3 productos",
    eyebrow: "Rutina completa · barrera",
    description: "Kit de inicio con tónico, ampolla y crema de la línea The Real Noni en tamaño mini. Sus fórmulas ayudan a recuperar hidratación, confort y luminosidad. Es práctico para viajar, regalar o conocer la línea.",
    skin: "Piel normal, seca, sensible o deshidratada.",
    use: "Usá los productos de la textura más liviana a la más cremosa.",
    price: 42900,
    transfer: 44910,
    image: "/products-v11/celimax-noni.webp",
    accent: "#8db88b",
  },
  {
    brand: "CELIMAX",
    name: "The Vita A Retinol Shot Tightening Serum",
    size: "30 ml",
    eyebrow: "Retinol · textura · líneas",
    description: "Sérum nocturno con retinol, péptidos, pantenol y tecnología de microespículas. Ayuda a mejorar progresivamente la apariencia de líneas finas, poros visibles, falta de firmeza y textura irregular.",
    skin: "Piel acostumbrada a activos que busque renovar textura.",
    use: "Introducí de noche, 1 o 2 veces por semana. No mezcles con otros exfoliantes.",
    price: 44900,
    transfer: 49410,
    image: "/products-v11/celimax-retinol.webp",
    accent: "#c8c6c1",
  },
  {
    brand: "CELIMAX",
    name: "Dual Barrier Skin Wearable Cream",
    size: "50 ml",
    eyebrow: "Ceramidas · barrera cutánea",
    description: "Crema hidratante con ceramidas, pantenol, ácido hialurónico, colesterol y fitoesfingosina. Ayuda a mantener la humedad y reforzar la barrera cuando la piel está seca, sensible o sensibilizada.",
    skin: "Piel seca, sensible, deshidratada o con barrera alterada.",
    use: "Aplicá como último paso, de mañana o de noche.",
    price: 49900,
    transfer: 53910,
    image: "/products-v11/celimax-barrier.webp",
    accent: "#d8d6cf",
  },
  {
    brand: "MEDICUBE",
    name: "One Day Exosome Shot Pore Serum 2000",
    size: "30 ml",
    eyebrow: "Poros · textura irregular",
    description: "Sérum intensivo con microespículas, exosomas de origen lactobacillus y una combinación de AHA, BHA y PHA. Ayuda a mejorar la apariencia de poros, textura irregular, exceso de sebo y puntos negros.",
    skin: "Piel mixta o grasa acostumbrada a activos.",
    use: "Usá de noche, gradualmente, dentro de una rutina simple. Puede sentirse cosquilleo.",
    price: 54900,
    transfer: 58410,
    image: "/products-v11/medicube-exosome.webp",
    accent: "#819ec7",
  },
  {
    brand: "MEDICUBE",
    name: "Collagen Night Wrapping Mask",
    size: "75 ml",
    eyebrow: "Mascarilla nocturna · glow",
    description: "Mascarilla nocturna tipo wrapping que forma una película flexible y se retira por la mañana. Ayuda a reducir la pérdida de humedad y a que la piel se vea más lisa, luminosa y rellena al despertar.",
    skin: "Todo tipo de piel que busque hidratación y luminosidad.",
    use: "Aplicá una capa uniforme como último paso, dejá secar y retirala al despertar.",
    price: 47900,
    transfer: 53910,
    image: "/products-v11/medicube-mask.webp",
    accent: "#d7a49d",
  },
  {
    brand: "MEDICUBE",
    name: "Triple Collagen Serum 4.0",
    size: "55 ml",
    eyebrow: "Hidratación · elasticidad",
    description: "Sérum nutritivo y liviano con complejo de colágeno, niacinamida y ácido hialurónico. Ayuda a mantener la hidratación, mejorar la apariencia de elasticidad y devolver luminosidad a pieles opacas.",
    skin: "Piel normal, seca o mixta con falta de luminosidad.",
    use: "Aplicá después del tónico, de mañana o de noche.",
    price: 47900,
    transfer: 53910,
    image: "/products-v11/medicube-serum.webp",
    accent: "#e0b4b5",
  },
  {
    brand: "MEDICUBE",
    name: "Collagen Niacinamide Jelly Cream",
    size: "50 ml",
    eyebrow: "Glass glow · suavidad",
    description: "Crema gel transparente con colágeno hidrolizado, niacinamida y escualano. Su textura jelly aporta hidratación y un acabado pulido y luminoso sin la pesadez de una crema tradicional.",
    skin: "Todo tipo de piel; ajustá la cantidad si tu piel es grasa.",
    use: "Aplicá después de tus sérums, de mañana o de noche.",
    price: 49900,
    transfer: 52110,
    image: "/products-v11/medicube-jelly.webp",
    accent: "#e8a9b4",
    soldOut: true,
  },
  {
    brand: "MEDICUBE",
    name: "Deep Vita C Pad",
    size: "70 pads",
    eyebrow: "Vitamina C · marcas",
    description: "Pads tonificantes con espino amarillo, niacinamida, vitamina C derivada y gluconolactona. Ayudan a trabajar opacidad, tono irregular y marcas post-imperfecciones mientras aportan hidratación.",
    skin: "Todo tipo de piel con falta de luminosidad.",
    use: "Pasá un pad después de limpiar o dejalo unos minutos sobre una zona puntual.",
    price: 49900,
    transfer: 49410,
    image: "/products-v11/medicube-vitac.webp",
    accent: "#b49a76",
  },
  {
    brand: "MEDICUBE",
    name: "Zero Pore Pad 2.0",
    size: "70 pads",
    eyebrow: "AHA + BHA · poros",
    description: "Pads de doble textura formulados con AHA, BHA y extractos botánicos. Ayudan a retirar células muertas y exceso de sebo para que poros, puntos negros y textura áspera se vean más refinados.",
    skin: "Piel mixta, grasa o normal con poros y textura.",
    use: "Empezá 2 o 3 noches por semana y usá protector solar al día siguiente.",
    price: 54900,
    transfer: 62910,
    image: "/products-v11/medicube-pore.webp",
    accent: "#84a5cf",
  },
];
