export type Product = {
  brand: "SKIN1004" | "CELIMAX" | "MEDICUBE" | "BEAUTY OF JOSEON" | "DR. ALTHEA" | "ANUA" | "ANUA + DR. ALTHEA" | "MEDICUBE + DR. ALTHEA";
  name: string;
  size: string;
  eyebrow: string;
  description: string;
  skin: string;
  use: string;
  price: number;
  transfer?: number;
  image: string;
  imageScene?: boolean;
  accent: string;
  soldOut?: boolean;
  preorder?: boolean;
};

export const products: Product[] = [
  {
    brand: "SKIN1004",
    name: "Madagascar Centella Light Cleansing Oil",
    size: "200 ml",
    eyebrow: "Doble limpieza · maquillaje · SPF",
    description: "Aceite limpiador ligero que ayuda a disolver maquillaje, protector solar y exceso de sebo. Su fórmula con centella y aceites botánicos emulsiona al contacto con agua y se enjuaga sin dejar una sensación pesada.",
    skin: "Primera etapa de la doble limpieza, especialmente para retirar maquillaje, protector solar e impurezas oleosas.",
    use: "Aplicar sobre rostro y manos secos. Masajear suavemente, agregar un poco de agua hasta que el aceite emulsione y tome una textura lechosa, y luego enjuagar. Continuar con un limpiador base agua si se realiza doble limpieza.",
    price: 60900,
    transfer: 49900,
    image: "/products-edited/skin1004-cleansing.jpeg",
    accent: "#e9d2a7",
  },
  {
    brand: "SKIN1004",
    name: "Hyalu-Cica Water-Fit Sun Serum SPF50+ PA++++",
    size: "50 ml",
    eyebrow: "SPF · hidratación",
    description: "Protector solar de textura sérum que combina centella asiática y ácido hialurónico. Se absorbe rápido, no deja rastro blanco y ofrece un acabado luminoso y liviano que funciona muy bien debajo del maquillaje.",
    skin: "Piel normal, seca, mixta o sensible.",
    use: "Usá una cantidad generosa como último paso de la mañana y reaplicá.",
    price: 56000,
    transfer: 45900,
    image: "/products-edited/skin1004-sun.jpeg",
    accent: "#b9d8e8",
  },
  {
    brand: "SKIN1004",
    name: "Madagascar Centella Watergel Sheet Ampoule Mask",
    size: "25 ml",
    eyebrow: "Calma · hidratación intensa",
    description: "Mascarilla de tela con centella asiática, glicerina, manzanilla y ácido hialurónico. Aporta una sensación refrescante e hidratación inmediata cuando la piel se siente tirante o apagada.",
    skin: "Piel normal, mixta, sensible o deshidratada.",
    use: "Dejá actuar de 10 a 20 minutos y masajeá el excedente. No enjuagues.",
    price: 9200,
    transfer: 7500,
    image: "/products-v11/skin1004-mask.webp",
    imageScene: true,
    accent: "#d6c39f",
  },
  {
    brand: "CELIMAX",
    name: "Pore + Dark Spot Brightening Pad",
    size: "40 pads / 100 ml",
    eyebrow: "Manchas · luminosidad",
    description: "Pads tonificantes con niacinamida, ácido tranexámico, arbutina y ácido hialurónico. Ayudan a mejorar gradualmente la apariencia de manchas, marcas post-imperfecciones y tono desparejo mientras hidratan.",
    skin: "Todo tipo de piel con tono irregular o marcas visibles.",
    use: "Deslizá un pad después de limpiar o usalo como mini mascarilla puntual.",
    price: 48700,
    transfer: 39900,
    image: "/products-edited/celimax-pad.jpeg",
    accent: "#efd35f",
  },
  {
    brand: "CELIMAX",
    name: "The Real Noni Starter Kit",
    size: "3 productos",
    eyebrow: "Rutina completa · barrera",
    description: "Kit de inicio con tónico, ampolla y crema de la línea The Real Noni en tamaño mini. Sus fórmulas ayudan a recuperar hidratación, confort y luminosidad. Es práctico para viajar, regalar o conocer la línea.",
    skin: "Piel normal, seca, sensible o deshidratada.",
    use: "Usá los productos de la textura más liviana a la más cremosa.",
    price: 49400,
    transfer: 42900,
    image: "/products-v11/celimax-noni.webp",
    accent: "#8db88b",
  },
  {
    brand: "CELIMAX",
    name: "The Vita A Retinol Shot Tightening Serum",
    size: "30 ml",
    eyebrow: "Retinol · textura · líneas",
    description: "Sérum nocturno con retinol, péptidos, pantenol y tecnología de microespículas. Ayuda a mejorar progresivamente la apariencia de líneas finas, poros visibles, falta de firmeza y textura irregular.",
    skin: "Piel acostumbrada a activos que busque renovar textura.",
    use: "Introducí de noche, 1 o 2 veces por semana. No mezcles con otros exfoliantes.",
    price: 54800,
    transfer: 44900,
    image: "/products-edited/celimax-retinol.jpeg",
    accent: "#c8c6c1",
  },
  {
    brand: "CELIMAX",
    name: "Dual Barrier Skin Wearable Cream",
    size: "50 ml",
    eyebrow: "Ceramidas · barrera",
    description: "Crema hidratante con ceramidas, pantenol, ácido hialurónico, colesterol y fitoesfingosina. Ayuda a mantener la humedad y reforzar la barrera cuando la piel está seca, sensible o sensibilizada.",
    skin: "Piel seca, sensible, deshidratada o con barrera alterada.",
    use: "Aplicá como último paso, de mañana o de noche.",
    price: 60900,
    transfer: 49900,
    image: "/products-edited/celimax-barrier.jpeg",
    accent: "#d8d6cf",
  },
  {
    brand: "MEDICUBE",
    name: "One Day Exosome Shot Pore Serum 2000",
    size: "30 ml",
    eyebrow: "Poros · textura",
    description: "Sérum intensivo con microespículas, exosomas de origen lactobacillus y una combinación de AHA, BHA y PHA. Ayuda a mejorar la apariencia de poros, textura irregular, exceso de sebo y puntos negros.",
    skin: "Piel mixta o grasa acostumbrada a activos.",
    use: "Usá de noche, gradualmente, dentro de una rutina simple. Puede sentirse cosquilleo.",
    price: 59700,
    transfer: 48900,
    image: "/products-edited/medicube-exosome.jpeg",
    accent: "#819ec7",
  },
  {
    brand: "MEDICUBE",
    name: "Collagen Night Wrapping Mask",
    size: "75 ml",
    eyebrow: "Mascarilla · glow",
    description: "Mascarilla nocturna tipo wrapping que forma una película flexible y se retira por la mañana. Ayuda a reducir la pérdida de humedad y a que la piel se vea más lisa, luminosa y rellena al despertar.",
    skin: "Todo tipo de piel que busque hidratación y luminosidad.",
    use: "Aplicá una capa uniforme como último paso, dejá secar y retirala al despertar.",
    price: 60900,
    transfer: 49900,
    image: "/products-edited/medicube-mask.jpeg",
    accent: "#d7a49d",
  },
  {
    brand: "MEDICUBE",
    name: "Triple Collagen Serum 4.0",
    size: "55 ml",
    eyebrow: "Hidratación · elasticidad",
    description: "Sérum nutritivo y liviano con complejo de colágeno, niacinamida y ácido hialurónico. Ayuda a mantener la hidratación, mejorar la apariencia de elasticidad y devolver luminosidad a pieles opacas.",
    skin: "Piel normal, seca o mixta con falta de luminosidad.",
    use: "Aplicá después del tónico, de mañana o de noche.",
    price: 58500,
    transfer: 47900,
    image: "/products-edited/medicube-serum.jpeg",
    accent: "#e0b4b5",
  },
  {
    brand: "MEDICUBE",
    name: "Collagen Niacinamide Jelly Cream",
    size: "110 ml",
    eyebrow: "Hidratación · glow · elasticidad",
    description: "Crema hidratante transparente de textura jelly que aporta hidratación y un acabado luminoso tipo glass skin. Su fórmula con niacinamida, colágeno hidrolizado y escualano ayuda a dejar la piel más suave, tersa y con aspecto elástico.",
    skin: "Piel deshidratada, opaca o con pérdida de elasticidad que busca una crema de textura jelly y acabado luminoso.",
    use: "Aplicar como último paso de la rutina, después de los sérums. Puede utilizarse por la mañana o por la noche.",
    price: 64600,
    transfer: 52900,
    image: "/products-edited/medicube-jelly.jpeg",
    accent: "#e8a9b4",
  },
  {
    brand: "MEDICUBE",
    name: "Deep Vita C Pad",
    size: "70 pads",
    eyebrow: "Vitamina C · marcas",
    description: "Pads tonificantes con espino amarillo, niacinamida, vitamina C derivada y gluconolactona. Ayudan a trabajar opacidad, tono irregular y marcas post-imperfecciones mientras aportan hidratación.",
    skin: "Todo tipo de piel con falta de luminosidad.",
    use: "Pasá un pad después de limpiar o dejalo unos minutos sobre una zona puntual.",
    price: 60900,
    transfer: 49900,
    image: "/products-edited/medicube-vitac.jpeg",
    accent: "#b49a76",
  },
  {
    brand: "MEDICUBE",
    name: "Zero Pore Pad 2.0",
    size: "70 pads",
    eyebrow: "AHA + BHA · poros",
    description: "Pads de doble textura formulados con AHA, BHA y extractos botánicos. Ayudan a retirar células muertas y exceso de sebo para que poros, puntos negros y textura áspera se vean más refinados.",
    skin: "Piel mixta, grasa o normal con poros y textura.",
    use: "Empezá 2 o 3 noches por semana y usá protector solar al día siguiente.",
    price: 64600,
    transfer: 52900,
    image: "/products-edited/medicube-pore.jpeg",
    accent: "#84a5cf",
  },
  {
    brand: "SKIN1004",
    name: "Madagascar Centella Poremizing Deep Cleansing Foam",
    size: "125 ml",
    eyebrow: "Poros · limpieza profunda · sebo",
    description: "Espuma limpiadora rica y cremosa formulada para retirar impurezas y exceso de sebo. Su combinación de sales minerales, kaolin y papaina ayuda a realizar una limpieza profunda y una exfoliación suave, favoreciendo una piel más limpia y una textura más uniforme.",
    skin: "Piel grasa, mixta o normal con exceso de sebo, poros visibles o textura irregular.",
    use: "Aplicar una pequeña cantidad sobre las manos húmedas. Agregar agua y generar espuma. Masajear suavemente sobre el rostro húmedo evitando el áárea de los ojos. Enjuagar completamente.",
    price: 48700,
    transfer: 39900,
    image: "/products-edited/skin1004-poremizing-foam.jpeg",
    accent: "#e5b4b7",
  },
  {
    brand: "SKIN1004",
    name: "Madagascar Centella Ampoule Foam",
    size: "125 ml",
    eyebrow: "Limpieza suave · hidratación",
    description: "Limpiador facial espumoso de pH aproximado 5 diseñado para retirar impurezas y residuos sin dejar una sensación excesivamente tirante. Ayuda a limpiar mientras mantiene una sensación confortable e hidratada.",
    skin: "Piel normal, sensible o deshidratada que busca limpieza diaria suave.",
    use: "Aplicar una pequeña cantidad sobre las manos húmedas. Generar espuma con agua. Masajear suavemente sobre el rostro húmedo. Enjuagar completamente.",
    price: 48700,
    transfer: 39900,
    image: "/products-edited/skin1004-ampoule-foam.jpeg",
    accent: "#b78759",
  },
  {
    brand: "BEAUTY OF JOSEON",
    name: "Daily Tinted Fluid Sunscreen SPF 40 LP110",
    size: "50 ml",
    eyebrow: "SPF 40 · cobertura ligera",
    description: "Protector solar mineral con color que combina protección SPF 40 de amplio espectro con una cobertura ligera y translúcida. Su textura fluida ayuda a unificar visualmente el tono sin sentirse como una base pesada. Acabado natural.",
    skin: "Uso diario para quienes buscan protector solar con color, cobertura ligera y acabado natural.",
    use: "Agitar bien antes de usar. Aplicar generosamente como último paso de la rutina de skincare. Distribuir de manera uniforme sobre el rostro. Reaplicar durante el día.",
    price: 68200,
    transfer: 55900,
    image: "/products-edited/boj-tinted-sunscreen.jpeg",
    accent: "#d4a991",
  },
  {
    brand: "DR. ALTHEA",
    name: "345 Relief Cream",
    size: "50 ml",
    eyebrow: "Barrera · calma · marcas",
    description: "Crema hidratante de textura ligera formulada especialmente para piel sensibilizada o con tendencia a imperfecciones. Ayuda a mantener la hidratación, calmar la piel y reforzar la barrera cutánea. Orientada al cuidado visible de marcas.",
    skin: "Piel sensible, sensibilizada, barrera alterada o marcas post-brote.",
    use: "Aplicar como último paso de la rutina. Distribuir una cantidad adecuada sobre rostro y cuello. Presionar suavemente hasta absorber.",
    price: 65800,
    transfer: 53900,
    image: "/products-edited/dr-althea-345.jpeg",
    accent: "#a9b9b1",
  },
  {
    brand: "CELIMAX",
    name: "The Vita-A Retinal Shot Tightening Booster",
    size: "15 ml",
    eyebrow: "0,1% retinal · textura · firmeza",
    description: "Booster nocturno formulado con retinal para ayudar a mejorar gradualmente la apariencia de líneas finas, textura irregular, pérdida de firmeza y poros visibles. Combina retinal con péptidos y la tecnología A-Shot.",
    skin: "Líneas finas, textura irregular, apariencia de poros o pérdida de firmeza.",
    use: "Utilizar por la noche. Aplicar una pequeña cantidad. Si es la primera vez, usar noche por medio durante las primeras dos semanas. Acompañar con hidratante. Usar protector solar de día.",
    price: 54800,
    transfer: 44900,
    image: "/products-edited/celimax-retinal.jpeg",
    accent: "#d7dd41",
    preorder: true,
  },
  {
    brand: "BEAUTY OF JOSEON",
    name: "Revive Eye Serum: Ginseng + Retinal",
    size: "30 ml",
    eyebrow: "Líneas finas · firmeza · glow",
    description: "Sérum para el contorno de ojos formulado con ginseng y retinal. Ayuda a mejorar gradualmente la apariencia de líneas finas y firmeza mientras aporta hidratación y luminosidad. Textura ligera y de rápida absorción.",
    skin: "Primeras líneas, contorno seco, aspecto cansado o falta de luminosidad.",
    use: "Presionar 1 o 2 veces. Aplicar con el dedo anular alrededor del contorno. Dar suaves toques hasta absorber. Finalizar con protector solar. Consultar a un profesional si hay embarazo o lactancia.",
    price: 52400,
    transfer: 42900,
    image: "/products-edited/boj-eye-serum.jpeg",
    accent: "#efdfd4",
  },
  {
    brand: "ANUA",
    name: "Azelaic Acid 10 Hyaluron Redness Soothing Serum",
    size: "30 ml",
    eyebrow: "Rojeces · imperfecciones · textura",
    description: "Sérum ligero y no comedogénico formulado con 10% de ácido azelaico. Ayuda a calmar el aspecto del enrojecimiento, mejorar visualmente imperfecciones y marcas y equilibrar el exceso de sebo.",
    skin: "Piel sensible, grasa o mixta con rojeces, imperfecciones o textura irregular.",
    use: "Comenzar utilizando 1-2 gotas, 1-2 veces por semana e ir aumentando. Aplicar después del tónico y antes de la crema. Finalizar con protector solar de día.",
    price: 63400,
    transfer: 51900,
    image: "/products-edited/anua-azelaic.jpeg",
    accent: "#76c04f",
  },
  {
    brand: "SKIN1004",
    name: "Madagascar Centella Toning Toner",
    size: "210 ml",
    eyebrow: "PHA · exfoliación · textura",
    description: "Tónico acuoso formulado con PHA para realizar una exfoliación superficial suave. Ayuda a retirar gradualmente exceso de sebo y células muertas mientras aporta efecto calmante y favorece una textura más uniforme.",
    skin: "Piel normal, sensible o mixta con textura irregular o piel opaca.",
    use: "Después de la limpieza, aplicar sobre un algodón o con las manos. Distribuir suavemente sobre rostro y cuello. Continuar con sérum y crema hidratante.",
    price: 48700,
    transfer: 39900,
    image: "/products-edited/skin1004-toner.jpeg",
    accent: "#c29d60",
  },
  {
    brand: "MEDICUBE",
    name: "TXA Niacinamide 15% Serum",
    size: "30 ml",
    eyebrow: "Manchas · tono · luminosidad",
    description: "Sérum concentrado para trabajar la apariencia de manchas, marcas post-brote y tono desigual. Combina 5% de ácido tranexámico, 10% de niacinamida y 2% de arbutina, junto con ingredientes hidratantes, en una textura ligera.",
    skin: "Piel con manchas, marcas post-brote, tono irregular u opacidad.",
    use: "Aplicar unas gotas después del tónico y antes de la crema hidratante. Puede utilizarse por la mañana o por la noche. Durante el día, finalizar siempre con protector solar.",
    price: 59700,
    transfer: 48900,
    image: "/products-edited/medicube-txa-serum.jpeg",
    accent: "#eb7c8a",
    preorder: true,
  },
  {
    brand: "DR. ALTHEA",
    name: "Vitamin C Boosting Serum",
    size: "30 ml",
    eyebrow: "Manchas · luminosidad · tono",
    description: "Sérum iluminador formulado para ayudar a mejorar la apariencia de manchas, marcas post-brote y tono desigual. Combina agua de espino amarillo, ácido tranexámico, niacinamida, derivados de vitamina C y alpha-arbutin para aportar luminosidad sin dejar de lado la hidratación.",
    skin: "Piel apagada o con manchas, marcas posteriores a brotes y tono irregular.",
    use: "Aplicar unas gotas después de la limpieza y el tónico. Continuar con crema hidratante. Puede utilizarse por la mañana o por la noche; durante el día finalizar siempre con protector solar.",
    price: 60900,
    transfer: 49900,
    image: "/products-edited/dr-althea-vit-c.jpeg",
    accent: "#d8853b",
    preorder: true,
  },
  {
    brand: "SKIN1004",
    name: "Madagascar Centella Probio-Cica Bakuchiol Eye Cream",
    size: "20 ml",
    eyebrow: "Líneas · firmeza · hidratación",
    description: "Contorno de ojos con centella fermentada y bakuchiol que ayuda a mejorar visualmente la apariencia de líneas finas y firmeza mientras aporta hidratación a la zona. También contiene ceramida y ácido hialurónico para mantener el contorno confortable.",
    skin: "Contornos normales o secos con primeras líneas, falta de firmeza o deshidratación.",
    use: "Aplicar una pequeña cantidad alrededor del contorno de ojos y masajear suavemente desde el interior hacia el exterior hasta absorber.",
    price: 54800,
    transfer: 44900,
    image: "/products-edited/skin1004-probio-cica-eye.jpeg",
    accent: "#b09b85",
  },
  {
    brand: "MEDICUBE",
    name: "PDRN Pink Collagen Capsule Cream",
    size: "55 g",
    eyebrow: "Glow · hidratación · elasticidad",
    description: "Crema de doble textura que combina cápsulas rosadas con un gel transparente para aportar hidratación y luminosidad y ayudar a mejorar la apariencia de elasticidad y tono desigual. Su fórmula incluye PDRN de salmón, colágeno, ácido hialurónico y niacinamida.",
    skin: "Piel deshidratada, apagada o con pérdida de elasticidad que busca un acabado luminoso.",
    use: "Mezclar las cápsulas con el gel antes de aplicar. Utilizar más gel para una textura ligera o una mayor proporción de cápsulas para una sensación más nutritiva. Aplicar después del sérum, por la mañana o por la noche.",
    price: 73100,
    transfer: 59900,
    image: "/products-edited/medicube-pdrn-capsule.jpeg",
    accent: "#f4a2b9",
  },
  {
    brand: "SKIN1004",
    name: "Dúo Clean & Balance",
    size: "2 productos",
    eyebrow: "Limpieza · frescura · equilibrio",
    description: "Una dupla esencial para limpiar, refrescar y preparar la piel. El Madagascar Centella Ampoule Foam elimina impurezas y exceso de sebo sin dejar sensación tirante, mientras que el Madagascar Centella Toning Toner ayuda a mantener la piel suave, equilibrada y lista para los siguientes pasos de la rutina.",
    skin: "Piel mixta, grasa o con tendencia a imperfecciones. También para quienes buscan una rutina diaria sencilla que deje la piel limpia, fresca y equilibrada.",
    use: "1. Aplicar el Madagascar Centella Ampoule Foam sobre el rostro húmedo, masajear suavemente hasta formar espuma y enjuagar. 2. Aplicar luego el Madagascar Centella Toning Toner sobre la piel limpia con las manos o con un pad de algodón. 3. Continuar con serum o ampoule, crema hidratante y, durante el día, protector solar.",
    price: 91400,
    transfer: 74900,
    image: "/products/duo-doble-limpieza.jpeg",
    accent: "#c8a24e",
  },
  {
    brand: "MEDICUBE",
    name: "Dúo Glass Skin",
    size: "2 productos",
    eyebrow: "Hidratación · elasticidad · glow",
    description: "Dúo con Triple Collagen Serum 4.0 y Collagen Jelly Cream para potenciar hidratación, luminosidad y elasticidad. Sus texturas se complementan para dejar la piel con un aspecto más suave, relleno y radiante.",
    skin: "Piel normal, seca, deshidratada u opaca que busca potenciar el efecto glass skin.",
    use: "Aplicá primero el Triple Collagen Serum sobre la piel limpia y continuá con la Jelly Cream. Podés utilizar el dúo de mañana y/o de noche.",
    price: 114600,
    transfer: 93900,
    image: "/products/duo-glass-skin.jpeg",
    accent: "#e0b4b5",
  },
  {
    brand: "CELIMAX",
    name: "Dúo Anti-Age",
    size: "2 productos",
    eyebrow: "Renovación · firmeza · textura",
    description: "Dúo con Retinol Shot Tightening Serum y Vita-A Retinal Shot Tightening Booster para trabajar signos visibles de la edad, textura irregular y pérdida de firmeza mediante una rutina progresiva con vitamina A.",
    skin: "Piel con líneas finas, textura irregular, poros visibles o pérdida de elasticidad. Recomendado especialmente para quienes ya incorporan retinoides a su rutina.",
    use: "Utilizalos de noche e incorporalos de forma progresiva. Podés alternar el Retinol Shot y el Retinal Shot según la tolerancia de tu piel. Durante el día, usá siempre protector solar.",
    price: 102400,
    transfer: 83900,
    image: "/products/duo-antiage.jpeg",
    accent: "#c8c64a",
  },
  {
    brand: "MEDICUBE",
    name: "Dúo Poros & Textura",
    size: "2 productos",
    eyebrow: "Poros · textura · renovación",
    description: "Dúo con Zero Pore Pad 2.0 y Exosome Shot 2000 pensado para mejorar la apariencia de los poros y suavizar la textura irregular. Ideal para sumar renovación a una rutina enfocada en conseguir una superficie más lisa y uniforme.",
    skin: "Piel con poros visibles, textura irregular, puntos negros o tendencia al exceso de sebo.",
    use: "Incorporá ambos productos de forma progresiva. Podés alternarlos por la noche según la tolerancia de tu piel y completar siempre la rutina con hidratación.",
    price: 115800,
    transfer: 94900,
    image: "/products/duo-poros-textura.jpeg",
    accent: "#5f8cc7",
  },
  {
    brand: "ANUA + DR. ALTHEA",
    name: "Dúo Calm & Clear",
    size: "2 productos",
    eyebrow: "Marcas · rojeces · calma",
    description: "Dúo con Azelaic Acid 10% y 345 Relief Cream que combina tratamiento e hidratación en una misma rutina. Ayuda a mejorar la apariencia de marcas post-imperfecciones y rojeces mientras acompaña la barrera de la piel.",
    skin: "Piel con imperfecciones, rojeces, marcas post-granito o tendencia a sensibilizarse.",
    use: "Aplicá primero el Azelaic Acid sobre la piel limpia y continuá con la 345 Relief Cream. Si recién incorporás ácido azelaico, comenzá de forma progresiva.",
    price: 119500,
    transfer: 97900,
    image: "/products/duo-calm-clear.jpeg",
    accent: "#76c04f",
  },
  {
    brand: "MEDICUBE + DR. ALTHEA",
    name: "Dúo Brightening",
    size: "2 productos",
    eyebrow: "Luminosidad · tono uniforme · glow",
    description: "Dúo con Deep Vita C Pad y Vitamin C Boosting Serum para potenciar la luminosidad y ayudar a mejorar la apariencia del tono desigual y las marcas. Combina dos pasos de tratamiento para una piel de aspecto más uniforme y radiante.",
    skin: "Piel opaca, apagada, con tono desigual o marcas visibles.",
    use: "Incorporá los pads de forma progresiva y continuá con el serum de vitamina C. Ajustá la frecuencia según la tolerancia de tu piel y, durante el día, finalizá siempre con protector solar.",
    price: 113400,
    transfer: 92900,
    image: "/products/duo-brightening.jpeg",
    accent: "#d8853b",
  },
];

/** Convierte el nombre del producto en un slug apto para URL (ej: "Dúo Glass Skin" -> "duo-glass-skin"). */
export const productSlug = (p: Pick<Product, "name">) =>
  p.name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/&/g, " y ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

export const getProductBySlug = (slug: string) => products.find((p) => productSlug(p) === slug);

export const productPath = (p: Pick<Product, "name">) => `/producto/${productSlug(p)}`;
